@startuml edr

entity users {
  * user_id: uuid <<generated>>
  email: string
  password_hash: string
  created_at: datetime
  updated_at: datetime
}

entity secrets {
  * secret_id: uuid <<generated>>
  user_id: uuid <<FK>>
  name: string
  type: varchar
  secret: byte
  meta: string
  created_at: datetime
  updated_at: datetime
}

entity vaults {
  * vault_id: uuid <<generated>>
  user_id: uuid <<FK>>
  name: string
  created_at: datetime
  updated_at: datetime
}

entity secret_vault {
  * secret_id: uuid <<FK>>
  * vault_id: uuid <<FK>>
}

users ||--{ secrets
users ||--{ vaults
secrets ||--{ secret_vault
vaults ||--{ secret_vault

@enduml
